spring.application.name=RLaaS
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379
spring.datasource.url=jdbc:postgresql://localhost:5432/rlaas
spring.datasource.username=postgres
spring.datasource.password=mfcj43ow
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true